# Generated by Django 6.0.6 on 2026-08-16 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textile', '0003_employee_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereport',
            name='price_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='textile.productprocessstep'),
        ),
        migrations.AlterField(
            model_name='productprocessstep',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='textile.product'),
        ),
    ]
